#%RAML 1.0 DataType
type: object
properties:
  objectName:
    type:  string | nil
    required: false
  fields: 
    type: string | nil
    required: false
  where: 
    type: object
    required: false