api:
  name: "pw-sf-sys-api"
  layer: "system"
  version: "v1"
  id: "19513879"
  
http:
  basePath: "/api/v1/*"
  port: "8081"
  host: "0.0.0.0"
  timeout: "30000"
  
salesforce:
  username: "sachin26.sharma@nttdata.com.muleuat"
  password: "![kBzmZcM+8uDoYnf29SyNkA==]"
  token: "![i8tUVeHhS9YHcA4jBistJTpw1z0Y4ZpKYuq4aLZz6Mo=]"
  url: "https://principalwine--uat.sandbox.my.salesforce.com/services/Soap/u/58.0"
  reconnectionStrategy:
    frequency: "5000"
    attempts: "2"