api:
  name: "pw-sf-sys-api"
  layer: "system"
  version: "v1"
  id: "19513879"
  
http:
  basePath: "/api/v1/*"
  port: "8081"
  host: "0.0.0.0"
  timeout: "30000"
  
salesforce:
  username: "sameet.bhole@nttdata.com.uat"
  password: "![kBzmZcM+8uDoYnf29SyNkA==]"
  token: "![3u4MDhoUfnhrtkSHOs2+XyeMox7Hw7ZvQzLdz5Dt6kk=]"
  url: "https://principalwine--uat.sandbox.my.salesforce.com/services/Soap/u/58.0"
  reconnectionStrategy:
    frequency: "5000"
    attempts: "2"