#%RAML 1.0 DataType 
type: object
properties:
  ID:
    type: string | nil
    required: false
  Email:
    type: string
    required: false
  Default:
    type: boolean
    required: false
  IncludeInEmail:
    type: boolean
    required: false
  Comment:
    type: string
    required: false
  MobilePhone:
    type: string
    required: false
  Name:
    type: string
    required: false
  Phone:
    type: string
    required: false
  Fax:
    type: string | nil
    required: false
  Website:
    type: string | nil
    required: false
  LastModifiedOn:
    type: string
    required: false
  